# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 SteamZero contributors
"""Contratos operacionais publicados para a central handheld.

Este módulo é a fonte de verdade da ligação backend → tela → controle. A QML
recebe este catálogo pelo ``/status`` e usa ``id`` para resolver método,
endpoint, confirmação, schema de entrada, semântica de job e rollback. Rotas
deliberadamente ausentes da GUI também aparecem, com justificativa explícita.
"""

from __future__ import annotations

from typing import Any

_STATES = ("ready", "empty", "degraded", "pending", "failed", "offline")


def _schema(*required: str, **properties: str) -> dict[str, Any]:
    return {
        "type": "object",
        "required": list(required),
        "properties": {name: {"type": kind} for name, kind in properties.items()},
        "additionalProperties": False,
    }


def _closed_schema(
    required: tuple[str, ...], properties: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    """Schema fechado quando a rota possui tipos JSON além de strings."""
    return {
        "type": "object",
        "required": list(required),
        "properties": properties,
        "additionalProperties": False,
    }


def _action(
    action_id: str,
    label: str,
    endpoint: str | None,
    *,
    service: str,
    screen: str,
    control: str,
    method: str = "POST",
    schema: dict[str, Any] | None = None,
    confirmation: str = "none",
    job: str = "synchronous",
    poll_endpoint: str | None = None,
    rollback_endpoint: str | None = None,
    enabled: bool = True,
    reason: str = "",
    applicable: bool = True,
    states: tuple[str, ...] = _STATES,
) -> dict[str, Any]:
    return {
        "id": action_id,
        "label": label,
        "enabled": enabled,
        "reason": reason,
        "service": service,
        "endpoint": endpoint,
        "method": method if endpoint else None,
        "screen": screen,
        "control": control,
        "states": list(states),
        "applicability": "applicable" if applicable else "not-applicable",
        "confirmation": {"required": confirmation != "none", "mode": confirmation},
        "inputSchema": schema or _schema(),
        "jobSemantics": {
            "kind": job,
            "states": (
                ["queued", "running", "succeeded", "failed", "cancelled"]
                if job == "asynchronous"
                else ["succeeded", "failed"]
            ),
            "pollEndpoint": poll_endpoint,
        },
        "rollback": {
            "supported": rollback_endpoint is not None,
            "endpoint": rollback_endpoint,
        },
    }


def handheld_ui_contracts() -> dict[str, Any]:
    """Retorna a matriz verificável consumida pela QML e pelos testes."""
    actions = [
        _action(
            "desktop.status",
            "Atualizar central",
            "/status",
            service="bridge",
            screen="global",
            control="refresh",
            method="GET",
        ),
        _action(
            "desktop.profile.plan",
            "Revisar perfil",
            "/plan",
            service="controller",
            screen="profiles",
            control="profile-plan",
            schema=_schema("profile", profile="string"),
        ),
        _action(
            "desktop.profile.apply",
            "Aplicar perfil",
            "/apply",
            service="controller",
            screen="profiles",
            control="profile-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/recover",
        ),
        _action(
            "desktop.profile.reset",
            "Aplicar modo seguro",
            "/reset",
            service="controller",
            screen="profiles",
            control="safe-reset",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/recover",
        ),
        _action(
            "desktop.recover",
            "Recuperar Desktop",
            "/recover",
            service="controller",
            screen="system",
            control="desktop-recover",
            confirmation="dialog",
        ),
        _action(
            "desktop.conflict.plan",
            "Revisar conflito",
            "/conflict/plan",
            service="controller",
            screen="overview",
            control="conflict-plan",
            schema=_schema("actionId", actionId="string"),
        ),
        _action(
            "desktop.conflict.apply",
            "Resolver conflito",
            "/conflict/apply",
            service="controller",
            screen="overview",
            control="conflict-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "component.list",
            "Listar componentes",
            "/component/list",
            service="components",
            screen="emulators",
            control="component-list",
            method="GET",
        ),
        _action(
            "component.status",
            "Consultar componente",
            "/component/status",
            service="components",
            screen="emulators",
            control="component-detail",
            schema=_schema("componentId", componentId="string"),
        ),
        _action(
            "component.verify",
            "Verificar componente",
            "/component/verify",
            service="components",
            screen="emulators",
            control="component-verify",
            schema=_schema("componentId", componentId="string"),
        ),
        _action(
            "component.matrix",
            "Consultar capacidades de componentes",
            "/component/matrix",
            service="components",
            screen="emulators",
            control="component-capability-matrix",
            method="GET",
        ),
        _action(
            "component.plan",
            "Revisar instalação",
            "/component/plan",
            service="components",
            screen="emulators",
            control="component-menu",
            schema=_schema("componentId", "action", componentId="string", action="string"),
        ),
        _action(
            "component.apply",
            "Aplicar componente",
            "/component/apply",
            service="components",
            screen="emulators",
            control="component-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            job="asynchronous",
            poll_endpoint="/emulation/job/status/{jobId}",
        ),
        _action(
            "component.launch",
            "Abrir componente",
            "/component/launch",
            service="components",
            screen="emulators",
            control="component-menu",
            schema=_schema("componentId", componentId="string"),
        ),
        _action(
            "component.open-config",
            "Abrir configuração do componente",
            None,
            service="components",
            screen="emulators",
            control="component-open-config",
            enabled=False,
            applicable=False,
            reason=(
                "Nenhum emulador ativo possui argumento oficial comprovado para abrir "
                "diretamente a configuração; consulte a matriz e abra a UI principal."
            ),
        ),
        _action(
            "component.open-config.matrix",
            "Consultar decisões de configuração",
            "/component/open-config/matrix",
            service="components",
            screen="emulators",
            control="component-open-config-matrix",
            method="GET",
        ),
        _action(
            "component.recovery.inspect",
            "Inspecionar recuperação de componentes",
            "/component/recovery/inspect",
            service="components",
            screen="system",
            control="component-recovery",
            method="GET",
        ),
        _action(
            "bios.status",
            "Consultar requisitos de BIOS",
            "/bios/status",
            service="emulation",
            screen="emulators",
            control="bios-status",
            method="GET",
        ),
        _action(
            "bios.audit",
            "Auditar store de BIOS",
            "/bios/audit",
            service="emulation",
            screen="emulators",
            control="bios-audit",
            method="GET",
        ),
        _action(
            "bios.sources",
            "Listar origens aprovadas de BIOS",
            "/bios/sources",
            service="emulation",
            screen="emulators",
            control="bios-source-selector",
            method="GET",
        ),
        _action(
            "bios.scan",
            "Selecionar e varrer BIOS",
            "/bios/scan",
            service="emulation",
            screen="emulators",
            control="bios-scan",
            schema=_schema("sourceId", sourceId="string"),
        ),
        _action(
            "bios.scan.status",
            "Consultar varredura de BIOS",
            "/bios/scan/status",
            service="emulation",
            screen="emulators",
            control="bios-scan-status",
            schema=_schema("scanId", scanId="string"),
        ),
        _action(
            "bios.import.plan",
            "Revisar importação de BIOS",
            "/bios/import/plan",
            service="emulation",
            screen="emulators",
            control="bios-import-plan",
            schema=_closed_schema(
                ("scanId",),
                {
                    "scanId": {"type": "string"},
                    "selection": {"type": "array", "items": {"type": "string"}},
                },
            ),
        ),
        _action(
            "bios.import.apply",
            "Confirmar importação de BIOS",
            "/bios/import/apply",
            service="emulation",
            screen="emulators",
            control="bios-import-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/bios/rollback/plan",
        ),
        _action(
            "bios.rollback.plan",
            "Revisar rollback de BIOS",
            "/bios/rollback/plan",
            service="emulation",
            screen="emulators",
            control="bios-rollback-plan",
            schema=_schema("operationId", operationId="string"),
        ),
        _action(
            "bios.rollback.apply",
            "Confirmar rollback de BIOS",
            "/bios/rollback/apply",
            service="emulation",
            screen="emulators",
            control="bios-rollback-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "component.recovery.plan",
            "Revisar recovery",
            "/component/recovery/plan",
            service="components",
            screen="system",
            control="component-recovery",
        ),
        _action(
            "component.recovery.apply",
            "Confirmar recovery",
            "/component/recovery/apply",
            service="components",
            screen="system",
            control="component-recovery-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "component.stop",
            "Revisar parada do componente",
            "/component/plan",
            service="components",
            screen="emulators",
            control="component-stop",
            schema=_schema("componentId", "action", componentId="string", action="string"),
            confirmation="dialog",
        ),
        _action(
            "component.history",
            "Consultar histórico do componente",
            "/component/history",
            service="components",
            screen="system",
            control="component-history",
            schema=_schema("componentId", componentId="string"),
        ),
        _action(
            "component.rollback.plan",
            "Revisar reversão do componente",
            "/component/rollback/plan",
            service="components",
            screen="system",
            control="component-history",
            schema=_schema(
                "componentId", "operationId", componentId="string", operationId="string"
            ),
        ),
        _action(
            "component.rollback.apply",
            "Confirmar reversão do componente",
            "/component/rollback/apply",
            service="components",
            screen="system",
            control="component-history-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "component.rollback",
            "Desfazer componente (legado)",
            None,
            service="components",
            screen="system",
            control="component-history-legacy",
            enabled=False,
            applicable=False,
            reason="Use o fluxo de revisão e confirmação de rollback do componente.",
        ),
        _action(
            "component.recover",
            "Recuperar componente",
            None,
            service="components",
            screen="system",
            control="component-recovery",
            enabled=False,
            reason=("Use Inspecionar recuperação, depois Revisar recovery e Confirmar recovery."),
            applicable=False,
        ),
        _action(
            "emulator.plan",
            "Revisar emulador",
            "/emulation/emulator/plan",
            service="emulation",
            screen="emulators",
            control="emulator-menu",
            schema=_schema("emulatorId", "action", emulatorId="string", action="string"),
        ),
        _action(
            "emulator.apply",
            "Aplicar no emulador",
            "/emulation/emulator/apply",
            service="emulation",
            screen="emulators",
            control="emulator-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "emulator.launch",
            "Abrir emulador",
            "/emulation/emulator/launch",
            service="emulation",
            screen="emulators",
            control="emulator-menu",
            schema=_schema("emulatorId", emulatorId="string"),
        ),
        _action(
            "emulator.stop",
            "Parar emulador",
            "/emulation/emulator/stop",
            service="emulation",
            screen="emulators",
            control="emulator-menu",
            schema=_schema("emulatorId", emulatorId="string"),
            confirmation="dialog",
        ),
        _action(
            "game.launch",
            "Jogar",
            "/emulation/game/launch",
            service="library",
            screen="library",
            control="game-primary",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "playtime.continue.emulation",
            "Continuar jogo emulado",
            "/emulation/game/launch",
            service="playtime",
            screen="overview",
            control="continue-playing",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "cloud.launch",
            "Abrir serviço cloud",
            "/cloud/launch",
            service="emulation",
            screen="emulation",
            control="cloud-primary",
            schema=_schema("platformId", platformId="string"),
        ),
        _action(
            "emulation.action.plan",
            "Revisar alteração",
            "/emulation/action/plan",
            service="emulation",
            screen="emulation",
            control="action-plan",
            schema=_closed_schema(
                ("actionId",),
                {
                    "actionId": {"type": "string"},
                    "path": {"type": "string"},
                    "paths": {"type": "array", "items": {"type": "string"}},
                    "targetFormat": {"type": "string"},
                    "titleId": {"type": "string"},
                    "emulatorId": {"type": "string"},
                    "version": {"type": "string"},
                    "gameId": {"type": "string"},
                    "selected": {"type": "boolean"},
                    "value": {"type": "boolean"},
                    "overwrite": {"type": "boolean"},
                    "approvedPaths": {"type": "array", "items": {"type": "string"}},
                    "deferAudit": {"type": "boolean"},
                    "steamUserId": {"type": "string"},
                    "mediaKinds": {"type": "array", "items": {"type": "string"}},
                    "mediaKind": {"type": "string"},
                },
            ),
        ),
        _action(
            "emulation.action.apply",
            "Confirmar alteração",
            "/emulation/action/apply",
            service="emulation",
            screen="emulation",
            control="action-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/emulation/action/rollback",
        ),
        _action(
            "emulation.action.rollback",
            "Desfazer alteração",
            "/emulation/action/rollback",
            service="emulation",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "library.scan",
            "Escanear biblioteca",
            "/emulation/library/scan",
            service="library",
            screen="library",
            control="scan",
            job="asynchronous",
            poll_endpoint="/emulation/job/status/{jobId}",
        ),
        _action(
            "job.status",
            "Ver tarefa",
            "/emulation/job/status",
            service="jobs",
            screen="tasks",
            control="task-row",
            schema=_schema("jobId", jobId="string"),
        ),
        _action(
            "jobs.list",
            "Listar tarefas",
            "/emulation/jobs",
            service="jobs",
            screen="tasks",
            control="task-center",
            method="GET",
        ),
        _action(
            "job.cancel",
            "Cancelar tarefa",
            "/emulation/job/cancel",
            service="jobs",
            screen="tasks",
            control="task-row-cancel",
            schema=_schema("jobId", jobId="string"),
            confirmation="dialog",
        ),
        _action(
            "job.retry",
            "Tentar novamente",
            "/emulation/job/retry",
            service="jobs",
            screen="tasks",
            control="task-row-retry",
            schema=_schema("jobId", jobId="string"),
        ),
        _action(
            "steam.open",
            "Abrir Steam",
            "/steam/open",
            service="steam",
            screen="steam",
            control="steam-action",
            schema=_schema("target", target="string"),
        ),
        _action(
            "steam.game.launch",
            "Jogar jogo Steam",
            "/steam/game/launch",
            service="library",
            screen="library",
            control="game-primary",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "playtime.continue.steam",
            "Continuar jogo Steam",
            "/steam/game/launch",
            service="playtime",
            screen="overview",
            control="continue-playing",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "playtime.recover.steam",
            "Recuperar sessão Steam",
            "/steam/gameplay/recover",
            service="playtime",
            screen="overview",
            control="continue-playing",
            schema=_schema("gameId", gameId="string"),
            confirmation="dialog",
        ),
        _action(
            "collections.list",
            "Ver coleções",
            "/collections",
            service="library",
            screen="overview",
            control="collection-summary",
            method="GET",
        ),
        _action(
            "collections.plan",
            "Revisar alteração de coleção",
            "/collections/plan",
            service="library",
            screen="overview",
            control="collection-edit",
            schema=_schema("action", action="object"),
            confirmation="dialog",
        ),
        _action(
            "collections.apply",
            "Aplicar alteração de coleção",
            "/collections/apply",
            service="library",
            screen="overview",
            control="collection-edit",
            schema=_schema(
                "planId",
                "confirmToken",
                planId="string",
                confirmToken="string",
            ),
            confirmation="dialog",
        ),
        _action(
            "library.health",
            "Ver saúde da coleção",
            "/library/health",
            service="library",
            screen="overview",
            control="library-health",
            method="GET",
        ),
        _action(
            "library.health.plan",
            "Revisar verificação anti-bitrot",
            "/library/health/plan",
            service="library",
            screen="overview",
            control="library-health-scan",
            schema=_schema(),
            confirmation="dialog",
        ),
        _action(
            "library.health.apply",
            "Executar verificação anti-bitrot",
            "/library/health/apply",
            service="library",
            screen="overview",
            control="library-health-scan",
            schema=_schema(
                "planId",
                "confirmToken",
                planId="string",
                confirmToken="string",
            ),
            confirmation="dialog",
        ),
        _action(
            "steam.input.open",
            "Configurar Steam Input",
            "/steam/input/open",
            service="steam",
            screen="steam",
            control="steam-input",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "hud.presets",
            "Consultar presets HUD",
            "/hud/presets",
            service="steam",
            screen="steam-gameplay",
            control="mangohud-presets",
            method="GET",
        ),
        _action(
            "steam.gameplay.plan",
            "Revisar perfil Steam",
            "/steam/gameplay/plan",
            service="steam",
            screen="steam",
            control="gameplay-plan",
            schema=_closed_schema(
                (
                    "gameId",
                    "scope",
                    "profile",
                    "fps",
                    "tdp",
                    "gpuMode",
                    "gpuClock",
                    "gamescope",
                    "gameMode",
                    "mangoHud",
                    "vkBasalt",
                    "upscaling",
                    "frameGeneration",
                    "controllerLayout",
                ),
                {
                    "gameId": {"type": "string"},
                    "scope": {"type": "string"},
                    "profile": {"type": "string"},
                    "fps": {"type": "integer"},
                    "tdp": {"type": ["integer", "null"]},
                    "gpuMode": {"type": "string"},
                    "gpuClock": {"type": ["integer", "null"]},
                    "gamescope": {"type": "boolean"},
                    "gameMode": {"type": "boolean"},
                    "mangoHud": {"type": "string"},
                    "vkBasalt": {"type": "string"},
                    "upscaling": {"type": "string"},
                    "frameGeneration": {"type": "string"},
                    "controllerLayout": {"type": "string"},
                },
            ),
        ),
        _action(
            "steam.gameplay.apply",
            "Aplicar perfil Steam",
            "/steam/gameplay/apply",
            service="steam",
            screen="steam",
            control="gameplay-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/steam/gameplay/rollback",
        ),
        _action(
            "steam.gameplay.rollback",
            "Desfazer perfil Steam",
            "/steam/gameplay/rollback",
            service="steam",
            screen="steam",
            control="gameplay-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "steam.gameplay.recover",
            "Recuperar perfil Steam",
            "/steam/gameplay/recover",
            service="steam",
            screen="steam",
            control="gameplay-recover",
            schema=_schema("gameId", gameId="string"),
            confirmation="dialog",
        ),
        _action(
            "steam.launch-options.plan",
            "Revisar opções de lançamento",
            "/steam/gameplay/launch-options/plan",
            service="steam",
            screen="steam",
            control="launch-options-plan",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "steam.launch-options.apply",
            "Aplicar opções de lançamento",
            "/steam/gameplay/launch-options/apply",
            service="steam",
            screen="steam",
            control="launch-options-apply",
            schema=_schema(
                "planId",
                "confirmToken",
                "gameId",
                planId="string",
                confirmToken="string",
                gameId="string",
            ),
            confirmation="token",
            rollback_endpoint="/steam/gameplay/launch-options/rollback",
        ),
        _action(
            "steam.launch-options.rollback",
            "Desfazer opções de lançamento",
            "/steam/gameplay/launch-options/rollback",
            service="steam",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "steam.maintenance.plan",
            "Revisar manutenção",
            "/steam/maintenance/plan",
            service="maintenance",
            screen="steam",
            control="maintenance-plan",
            schema=_schema("gameId", "categories", gameId="string", categories="array"),
        ),
        _action(
            "steam.maintenance.apply",
            "Executar manutenção",
            "/steam/maintenance/apply",
            service="maintenance",
            screen="steam",
            control="maintenance-apply",
            schema=_schema(
                "planId",
                "confirmToken",
                "confirmPhrase",
                planId="string",
                confirmToken="string",
                confirmPhrase="string",
            ),
            confirmation="phrase",
            rollback_endpoint="/steam/maintenance/recover",
        ),
        _action(
            "steam.maintenance.recover",
            "Recuperar manutenção",
            "/steam/maintenance/recover",
            service="maintenance",
            screen="system",
            control="maintenance-recover",
            confirmation="dialog",
        ),
        _action(
            "steam.media.plan",
            "Revisar publicação Steam",
            "/steam/media/plan",
            service="media",
            screen="media",
            control="steam-media-plan",
            schema=_schema(
                "gameId",
                "accountId",
                "packagePath",
                gameId="string",
                accountId="string",
                packagePath="string",
            ),
        ),
        _action(
            "steam.media.apply",
            "Publicar mídia na Steam",
            "/steam/media/apply",
            service="media",
            screen="media",
            control="steam-media-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            job="asynchronous",
            rollback_endpoint="/steam/media/rollback",
        ),
        _action(
            "steam.media.rollback",
            "Desfazer publicação Steam",
            "/steam/media/rollback",
            service="media",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "lsfg.plan",
            "Revisar LSFG",
            "/system/lsfg/plan",
            service="components",
            screen="system",
            control="lsfg-plan",
        ),
        _action(
            "lsfg.apply",
            "Instalar LSFG",
            "/system/lsfg/apply",
            service="components",
            screen="system",
            control="lsfg-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/system/lsfg/rollback",
        ),
        _action(
            "lsfg.rollback",
            "Desfazer LSFG",
            "/system/lsfg/rollback",
            service="components",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "keyboard.toggle",
            "Alternar teclado",
            "/keyboard",
            service="session",
            screen="global",
            control="keyboard",
            schema=_schema(action="string", language="string"),
        ),
        _action(
            "keyboard.settings",
            "Salvar conforto do teclado",
            "/keyboard/settings",
            service="session",
            screen="system",
            control="keyboard-settings",
            schema={
                "type": "object",
                "properties": {
                    "sound": {"type": "boolean"},
                    "haptic": {"type": "boolean"},
                    "theme": {"type": "string"},
                },
                "additionalProperties": False,
            },
        ),
        _action(
            "session.select",
            "Trocar sessão",
            "/session/select",
            service="session",
            screen="overview",
            control="session-switch",
            schema={
                "type": "object",
                "required": ["target"],
                "properties": {
                    "target": {"type": "string"},
                    "planId": {"type": "string"},
                    "confirmToken": {"type": "string"},
                },
                "additionalProperties": False,
            },
            confirmation="two-step",
        ),
        _action(
            "terminal.open",
            "Abrir terminal",
            "/ashyterm",
            service="session",
            screen="system",
            control="terminal",
        ),
        _action(
            "panel.autohide",
            "Alternar painel",
            "/panel/autohide",
            service="controller",
            screen="profiles",
            control="panel-toggle",
            schema=_schema("enable", enable="boolean"),
        ),
        _action(
            "credential.status",
            "Atualizar credenciais",
            "/scraping/credential/status",
            service="media",
            screen="media",
            control="credential-refresh",
        ),
        _action(
            "credential.save",
            "Salvar credencial",
            "/scraping/credential/save",
            service="media",
            screen="media",
            control="credential-save",
            schema=_schema("provider", "credentials", provider="string", credentials="object"),
            confirmation="dialog",
        ),
        _action(
            "credential.test",
            "Testar credencial",
            "/scraping/credential/test",
            service="media",
            screen="media",
            control="credential-test",
            schema=_schema("provider", provider="string"),
        ),
        _action(
            "credential.delete",
            "Remover credencial",
            "/scraping/credential/delete",
            service="media",
            screen="media",
            control="credential-delete",
            schema=_schema("provider", provider="string"),
            confirmation="dialog",
        ),
        _action(
            "provider.link",
            "Abrir documentação do provider",
            "/scraping/provider-link",
            service="media",
            screen="media",
            control="provider-link",
            schema=_schema("provider", "link", provider="string", link="string"),
        ),
        _action(
            "sync.status",
            "Ver fila de sincronização",
            None,
            service="sync",
            screen="sync",
            control="sync-summary",
            method="GET",
            enabled=False,
            reason=(
                "A fila é somente leitura no snapshot atual; retry/cancel ainda não "
                "possuem rota da bridge."
            ),
            applicable=False,
        ),
        _action(
            "profiles.history",
            "Ver histórico de perfis",
            None,
            service="steam",
            screen="steam",
            control="profile-history",
            method="GET",
            enabled=False,
            reason=(
                "A UI revisa diferenças antes de aplicar e oferece recovery, mas o store "
                "não publica uma linha do tempo de perfis pela bridge."
            ),
            applicable=False,
        ),
        _action(
            "operations.history",
            "Ver histórico de operações",
            "/system/operations",
            service="system",
            screen="system",
            control="operation-history",
            method="GET",
            schema=_schema(),
        ),
        _action(
            "operations.detail",
            "Ver detalhes da operação",
            "/system/operations/show",
            service="system",
            screen="system",
            control="operation-detail",
            method="POST",
            schema=_schema("operationId", operationId="string"),
        ),
        _action(
            "operations.rollback.plan",
            "Revisar rollback da operação",
            "/system/operations/rollback/plan",
            service="system",
            screen="system",
            control="operation-rollback",
            method="POST",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "operations.rollback.apply",
            "Confirmar rollback da operação",
            "/system/operations/rollback/apply",
            service="system",
            screen="system",
            control="operation-rollback",
            method="POST",
            schema=_schema(
                "planId",
                "confirmToken",
                planId="string",
                confirmToken="string",
            ),
            confirmation="dialog",
        ),
        _action(
            "state.export",
            "Exportar estado",
            "/system/diagnostics/export/plan",
            service="system",
            screen="system",
            control="diagnostics-export",
            schema=_schema("destination", "kind", destination="string", kind="string"),
            confirmation="dialog",
        ),
        _action(
            "admin.health",
            "Ver saúde administrativa",
            "/system/admin/health",
            service="system",
            screen="system",
            control="admin-health",
            method="GET",
            schema=_schema(),
        ),
        _action(
            "session.recovery",
            "Recuperar sessão de jogo",
            None,
            service="session",
            screen="system",
            control="session-recovery",
            enabled=False,
            reason=(
                "A recuperação de sessão pertence ao daemon e ainda não possui contrato Desktop."
            ),
            applicable=False,
        ),
        _action(
            "support.bundle",
            "Exportar pacote de suporte",
            "/system/diagnostics/export/plan",
            service="system",
            screen="system",
            control="support-bundle",
            schema=_schema("destination", "kind", destination="string", kind="string"),
            confirmation="dialog",
        ),
        _action(
            "diagnostics.export.apply",
            "Confirmar exportação revisada",
            "/system/diagnostics/export/apply",
            service="system",
            screen="system",
            control="diagnostics-export-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="dialog",
        ),
        # --- Compartilhamento de tela (ADR-0022) ---------------------------
        _action(
            "cast.discover",
            "Descobrir receptores",
            "/cast/discover",
            service="bridge",
            screen="cast",
            control="cast-discover",
            method="GET",
        ),
        _action(
            "cast.pair",
            "Parear receptor",
            "/cast/pair",
            service="bridge",
            screen="cast",
            control="cast-pair",
            schema=_schema("receiverId", receiverId="string", pin="string"),
        ),
        _action(
            "cast.start",
            "Iniciar transmissão",
            "/cast/start",
            service="bridge",
            screen="cast",
            control="cast-start",
            schema=_schema("receiverId", receiverId="string", profile="string", mode="string"),
        ),
        _action(
            "cast.stop",
            "Parar transmissão",
            "/cast/stop",
            service="bridge",
            screen="cast",
            control="cast-stop",
        ),
        _action(
            "cast.status",
            "Status da transmissão",
            "/cast/status",
            service="bridge",
            screen="cast",
            control="cast-status",
            method="GET",
        ),
        _action(
            "cast.sessions",
            "Sessões ativas",
            "/cast/sessions",
            service="bridge",
            screen="cast",
            control="cast-sessions",
            method="GET",
        ),
        # --- Tema --------------------------------------------------------
        _action(
            "theme.list",
            "Listar temas disponíveis",
            "/theme/list",
            service="system",
            screen="system",
            control="theme-list",
            method="GET",
        ),
        _action(
            "theme.apply",
            "Aplicar tema",
            "/theme/apply",
            service="system",
            screen="system",
            control="theme-apply",
            schema=_schema("themeId", themeId="string"),
        ),
        _action(
            "theme.apply.confirm",
            "Confirmar aplicação de tema",
            "/theme/apply/confirm",
            service="system",
            screen="system",
            control="theme-apply-confirm",
            schema=_schema("planId", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "theme.apply.rollback",
            "Reverter aplicação de tema",
            "/theme/apply/rollback",
            service="system",
            screen="system",
            control="theme-apply-rollback",
            schema=_schema("operationId", operationId="string"),
            rollback_endpoint="/theme/apply/rollback",
        ),
        # --- Editor de temas ----------------------------------------------
        _action(
            "theme.editor.load",
            "Carregar tema para edição",
            "/theme/editor/load",
            service="system",
            screen="system",
            control="theme-editor-load",
            method="GET",
            schema=_schema("themeId", themeId="string"),
        ),
        _action(
            "theme.import.package.inspect",
            "Examinar pacote de tema antes de importar",
            "/theme/import/package/inspect",
            service="system",
            screen="system",
            control="theme-import-package-inspect",
            schema=_schema("source", source="string"),
        ),
        _action(
            "theme.import.package.apply",
            "Importar pacote de tema SteamZero",
            "/theme/import/package/apply",
            service="system",
            screen="system",
            control="theme-import-package-apply",
            schema=_schema("source", source="string", overwrite="boolean", asCopy="boolean"),
        ),
        _action(
            "theme.catalog.list",
            "Listar temas ES-DE curados",
            "/theme/catalog/list",
            service="system",
            screen="system",
            control="theme-catalog-list",
            schema=_schema(),
        ),
        _action(
            "theme.catalog.install",
            "Instalar tema curado",
            "/theme/catalog/install",
            service="system",
            screen="system",
            control="theme-catalog-install",
            schema=_schema("themeId", themeId="string", overwrite="boolean"),
        ),
        _action(
            "theme.catalog.rollback",
            "Desfazer instalação de tema",
            "/theme/catalog/rollback",
            service="system",
            screen="system",
            control="theme-catalog-rollback",
            schema=_schema("themeId", "operationId", themeId="string", operationId="string"),
        ),
        _action(
            "theme.catalog.uninstall",
            "Remover tema instalado",
            "/theme/catalog/uninstall",
            service="system",
            screen="system",
            control="theme-catalog-uninstall",
            confirmation="explicit",
            schema=_schema("themeId", themeId="string"),
        ),
        _action(
            "theme.store.gc",
            "Recuperar espaço de assets sem dono",
            "/theme/store/gc",
            service="system",
            screen="system",
            control="theme-store-gc",
            confirmation="explicit",
            schema=_schema(apply="boolean"),
        ),
        _action(
            "theme.scene.render",
            "Renderizar a cena do tema instalado",
            "/theme/scene/render",
            service="system",
            screen="system",
            control="theme-scene-render",
            schema=_schema(
                "themeId",
                themeId="string",
                systemId="string",
                variant="string",
                colorScheme="string",
                fontSize="string",
                aspectRatio="string",
                synthetic="boolean",
            ),
        ),
        _action(
            "theme.scene.render-imported",
            "Renderizar cena importada (sem ativar)",
            "/theme/scene/render-imported",
            service="system",
            screen="system",
            control="theme-scene-render-imported",
            schema=_schema("sceneId", sceneId="string", synthetic="boolean"),
        ),
        _action(
            "theme.import.esde.inspect",
            "Examinar tema ES-DE antes de importar",
            "/theme/import/esde/inspect",
            service="system",
            screen="system",
            control="theme-import-esde-inspect",
            schema=_schema("source", source="string"),
        ),
        _action(
            "theme.import.esde.apply",
            "Importar esquema de tema ES-DE",
            "/theme/import/esde/apply",
            service="system",
            screen="system",
            control="theme-import-esde-apply",
            schema=_schema("source", source="string", scheme="string", name="string"),
        ),
        _action(
            "theme.import.retrofe.inspect",
            "Examinar cena RetroFE antes de importar",
            "/theme/import/retrofe/inspect",
            service="system",
            screen="system",
            control="theme-import-retrofe-inspect",
            schema=_schema("source", source="string"),
        ),
        _action(
            "theme.import.retrofe.apply",
            "Importar cena RetroFE compilada",
            "/theme/import/retrofe/apply",
            service="system",
            screen="system",
            control="theme-import-retrofe-apply",
            schema=_schema(
                "source",
                "layout",
                "sceneId",
                "name",
                "author",
                "license",
                source="string",
                layout="string",
                sceneId="string",
                name="string",
                author="string",
                license="string",
                overwrite="boolean",
            ),
        ),
        _action(
            "theme.editor.create",
            "Criar novo tema",
            "/theme/editor/create",
            service="system",
            screen="system",
            control="theme-editor-create",
            schema=_schema("name", name="string"),
        ),
        _action(
            "theme.editor.set-tokens",
            "Alterar tokens de tema",
            "/theme/editor/set-tokens",
            service="system",
            screen="system",
            control="theme-editor-set-tokens",
            schema=_schema("sessionId", sessionId="string", category="string", values="object"),
        ),
        _action(
            "theme.editor.set-metadata",
            "Alterar metadados de tema",
            "/theme/editor/set-metadata",
            service="system",
            screen="system",
            control="theme-editor-set-metadata",
            schema=_schema("sessionId", sessionId="string", field="string"),
        ),
        _action(
            "theme.editor.set-layout",
            "Alterar geometria declarativa do tema",
            "/theme/editor/set-layout",
            service="system",
            screen="system",
            control="theme-editor-set-layout",
            schema=_schema(
                "sessionId",
                "layoutId",
                "field",
                "value",
                sessionId="string",
                layoutId="string",
                field="string",
            ),
        ),
        _action(
            "theme.editor.set-media-recipe",
            "Alterar enquadramento de mídia do tema",
            "/theme/editor/set-media-recipe",
            service="system",
            screen="system",
            control="theme-editor-set-media-recipe",
            schema=_schema(
                "sessionId",
                "role",
                "field",
                "value",
                sessionId="string",
                role="string",
                field="string",
            ),
        ),
        _action(
            "theme.editor.edit-asset-recipe",
            "Editar receitas declarativas de assets",
            "/theme/editor/edit-asset-recipe",
            service="system",
            screen="themes",
            control="theme-editor-edit-asset-recipe",
            schema=_closed_schema(
                ("sessionId", "op"),
                {
                    "sessionId": {"type": "string"},
                    "op": {"type": "string"},
                    "recipe": {"type": "string"},
                    "sourceSlot": {"type": "string"},
                    "name": {"type": "string"},
                    "nodeType": {"type": "string"},
                    "index": {"type": "integer"},
                    "toIndex": {"type": "integer"},
                    "field": {"type": "string"},
                    "value": {"type": ["string", "number", "boolean"]},
                    "profileType": {"type": "string"},
                    "tier": {"type": "string"},
                    "breakpointId": {"type": "string"},
                    "priority": {"type": "integer"},
                    "minWidth": {"type": "integer"},
                    "maxWidth": {"type": "integer"},
                    "minHeight": {"type": "integer"},
                    "maxHeight": {"type": "integer"},
                },
            ),
        ),
        _action(
            "theme.editor.edit-effect",
            "Editar pilha de efeitos do tema",
            "/theme/editor/edit-effect",
            service="system",
            screen="system",
            control="theme-editor-edit-effect",
            schema=_schema(
                "sessionId",
                "stack",
                "op",
                sessionId="string",
                stack="string",
                op="string",
                effectType="string",
                param="string",
            ),
        ),
        _action(
            "theme.editor.edit-motion",
            "Editar keyframes e timelines do tema",
            "/theme/editor/edit-motion",
            service="system",
            screen="system",
            control="theme-editor-edit-motion",
            schema=_schema(
                "sessionId",
                "op",
                "timeline",
                sessionId="string",
                op="string",
                timeline="string",
                field="string",
            ),
        ),
        _action(
            "theme.editor.edit-binding",
            "Editar binding de metadado do layout",
            "/theme/editor/edit-binding",
            service="system",
            screen="system",
            control="theme-editor-edit-binding",
            schema=_schema(
                "sessionId",
                "layoutId",
                "prop",
                sessionId="string",
                layoutId="string",
                prop="string",
                binding="string",
            ),
        ),
        _action(
            "theme.editor.undo",
            "Desfazer última edição do tema",
            "/theme/editor/undo",
            service="system",
            screen="system",
            control="theme-editor-undo",
            schema=_schema("sessionId", sessionId="string"),
        ),
        _action(
            "theme.editor.redo",
            "Refazer edição do tema",
            "/theme/editor/redo",
            service="system",
            screen="system",
            control="theme-editor-redo",
            schema=_schema("sessionId", sessionId="string"),
        ),
        _action(
            "theme.editor.preview",
            "Preview ao vivo do tema editado",
            "/theme/editor/preview",
            service="system",
            screen="system",
            control="theme-editor-preview",
            schema=_schema(
                "sessionId",
                sessionId="string",
                performanceTier="string",
                viewportWidth="integer",
                viewportHeight="integer",
            ),
        ),
        _action(
            "theme.editor.save",
            "Salvar tema editado",
            "/theme/editor/save",
            service="system",
            screen="system",
            control="theme-editor-save",
            schema=_schema("sessionId", sessionId="string"),
        ),
        _action(
            "theme.editor.export",
            "Exportar tema como ZIP",
            "/theme/editor/export",
            service="system",
            screen="system",
            control="theme-editor-export",
            schema=_schema("sessionId", "destination", sessionId="string", destination="string"),
            confirmation="dialog",
        ),
        _action(
            "theme.editor.export.apply",
            "Confirmar exportação do tema",
            "/theme/editor/export/apply",
            service="system",
            screen="system",
            control="theme-editor-export",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="dialog",
        ),
        _action(
            "theme.editor.cancel",
            "Cancelar sessão de edição",
            "/theme/editor/cancel",
            service="system",
            screen="system",
            control="theme-editor-cancel",
            schema=_schema("sessionId", sessionId="string"),
        ),
        # --- Studio de Jornadas ------------------------------------------
        _action(
            "journey.studio.list",
            "Listar jornadas salvas",
            "/journey/studio/list",
            service="journey",
            screen="system",
            control="journey-studio-list",
            method="GET",
        ),
        _action(
            "journey.studio.catalog",
            "Consultar fontes e temas publicados",
            "/journey/studio/catalog",
            service="journey",
            screen="system",
            control="journey-studio-catalog",
            method="GET",
        ),
        _action(
            "journey.studio.create",
            "Criar jornada",
            "/journey/studio/create",
            service="journey",
            screen="system",
            control="journey-studio-create",
            schema=_closed_schema(
                ("name",), {"name": {"type": "string", "minLength": 1, "maxLength": 128}}
            ),
        ),
        _action(
            "journey.studio.load",
            "Abrir jornada salva",
            "/journey/studio/load",
            service="journey",
            screen="system",
            control="journey-studio-load",
            schema=_closed_schema(
                ("journeyId",), {"journeyId": {"type": "string", "minLength": 1}}
            ),
        ),
        _action(
            "journey.studio.transact",
            "Editar jornada",
            "/journey/studio/transact",
            service="journey",
            screen="system",
            control="journey-studio-edit",
            schema=_closed_schema(
                ("operation", "payload"),
                {
                    "operation": {"type": "string"},
                    # O servidor valida as propriedades internas pela operação.
                    "payload": {"type": "object"},
                },
            ),
        ),
        _action(
            "journey.studio.save",
            "Salvar jornada",
            "/journey/studio/save",
            service="journey",
            screen="system",
            control="journey-studio-save",
            schema=_closed_schema(
                ("sessionId", "overwrite"),
                {
                    "sessionId": {"type": "string", "minLength": 1},
                    "overwrite": {"type": "boolean"},
                },
            ),
        ),
        _action(
            "journey.studio.activate",
            "Ativar a jornada salva no Launcher",
            "/journey/studio/activate",
            service="journey",
            screen="system",
            control="journey-studio-activate",
            schema=_closed_schema(
                ("sessionId", "expectedGeneration"),
                {
                    "sessionId": {"type": "string", "minLength": 1},
                    "expectedGeneration": {"type": "integer", "minimum": 0},
                },
            ),
        ),
        _action(
            "journey.studio.preview",
            "Pré-visualizar menu da jornada",
            "/journey/studio/preview",
            service="journey",
            screen="system",
            control="journey-studio-preview",
            schema=_closed_schema(
                ("sessionId", "menuId"),
                {
                    "sessionId": {"type": "string", "minLength": 1},
                    "menuId": {"type": "string", "minLength": 1},
                    "contextFilters": {"type": "object"},
                },
            ),
        ),
        _action(
            "journey.studio.engine-preview",
            "Renderizar tema com os resultados da jornada",
            "/journey/studio/engine-preview",
            service="journey",
            screen="system",
            control="journey-studio-preview",
            schema=_closed_schema(
                ("sessionId", "menuId", "expectedGeneration"),
                {
                    "sessionId": {"type": "string", "minLength": 1},
                    "menuId": {"type": "string", "minLength": 1},
                    "expectedGeneration": {"type": "integer", "minimum": 0},
                },
            ),
        ),
        _action(
            "journey.studio.coverage",
            "Verificar cobertura visual e operacional",
            "/journey/studio/coverage",
            service="journey",
            screen="system",
            control="journey-studio-coverage",
            schema=_closed_schema(
                ("sessionId", "usedStages"),
                {
                    "sessionId": {"type": "string", "minLength": 1},
                    "usedStages": {"type": "array", "items": {"type": "string"}},
                },
            ),
        ),
        _action(
            "journey.studio.import",
            "Importar jornada como cópia",
            "/journey/studio/import",
            service="journey",
            screen="system",
            control="journey-studio-import",
            schema=_closed_schema(
                ("source", "copyName"),
                {
                    "source": {"type": "string", "minLength": 1},
                    "copyName": {"type": "string", "minLength": 1, "maxLength": 128},
                },
            ),
        ),
        _action(
            "journey.studio.export.prepare",
            "Preparar exportação da jornada",
            "/journey/studio/export/prepare",
            service="journey",
            screen="system",
            control="journey-studio-export",
            schema=_closed_schema(
                ("sessionId", "destination"),
                {
                    "sessionId": {"type": "string", "minLength": 1},
                    "destination": {"type": "string", "minLength": 1},
                },
            ),
        ),
        _action(
            "journey.studio.export.apply",
            "Confirmar exportação da jornada",
            "/journey/studio/export/apply",
            service="journey",
            screen="system",
            control="journey-studio-export",
            schema=_closed_schema(
                ("planId", "confirmToken"),
                {
                    "planId": {"type": "string", "minLength": 1},
                    "confirmToken": {"type": "string", "minLength": 1},
                },
            ),
            confirmation="token",
        ),
        _action(
            "journey.studio.undo",
            "Desfazer edição da jornada",
            "/journey/studio/undo",
            service="journey",
            screen="system",
            control="journey-studio-undo",
            schema=_closed_schema(
                ("sessionId",), {"sessionId": {"type": "string", "minLength": 1}}
            ),
        ),
        _action(
            "journey.studio.redo",
            "Refazer edição da jornada",
            "/journey/studio/redo",
            service="journey",
            screen="system",
            control="journey-studio-redo",
            schema=_closed_schema(
                ("sessionId",), {"sessionId": {"type": "string", "minLength": 1}}
            ),
        ),
    ]
    return {
        "schemaVersion": 1,
        "states": list(_STATES),
        "actions": actions,
        "byId": {action["id"]: action for action in actions},
    }
